apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: tenant-sandbox-gravitee
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "2"
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
