apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-knative
  namespace: kube-controllers
spec:
  template:
    spec:
      containers:
      - image: docker.io/berndinox/hello-knative
        env:
        - name: TARGET
          value: "Knative"
